<a href="https://colab.research.google.com/github/suryakokkiligadda2003/Python-mini-projects/blob/main/Python_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr1 = np.random.randint(1,2,(3,2))

In [5]:
arr1.shape

(3, 2)

In [6]:
result= np.dot(arr1,arr)

In [7]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[18 17 19]
 [15 15 13]
 [17 12 11]]


In [8]:
r2 = np.eye(3)
print(r1)

[[18 17 19]
 [15 15 13]
 [17 12 11]]


In [9]:
result2 = np.dot(r2,r1)

In [10]:
print(result2)

[[18. 17. 19.]
 [15. 15. 13.]
 [17. 12. 11.]]


In [13]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

arr3 = np.array